apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sample.fullname" . }}-vault-secrets
spec:
  provider: vault
  secretObjects: # Optional: Define this if you want to create Kubernetes secrets automatically
  - secretName: my-app-secrets
    type: Opaque
    data:
    {{- range .Values.vaultSecrets }}
    - key: {{ .name }}
      objectName: {{ .name }}
    {{- end }}
  parameters:
    vaultAddress: {{ .Values.vault.address }}
    roleName: {{ .Values.vault.roleName }}
    objects: |
      {{- range .Values.vaultSecrets }}
      - objectName: "{{ .name }}"
        secretPath: "{{ .secretPath }}"
        secretKey: "{{ .secretKey }}"
      {{- end }}